### ISSUE TITLE
SetQueryConfig overwrites Query parameter

### ISSUE THREAD

**Issue by addcninblue** [googleapis/google-cloud-go-testing#22]
https://github.com/googleapis/google-cloud-go-testing/blob/eb75b5d3b5349f64f4e398e2dbd76310dbc88672/bigquery/bqiface/adapters.go#L192

Here, since `q.Query.QueryConfig` is set to `c.QueryConfig`, the parameter `q` passed into `Query(q string)` is overwritten by the `QueryConfig`. This means that the string `q` is effectively useless, and does not mirror the behavior of the original `bigquery` library.

Testing file:
```
import (
	"context"

	"cloud.google.com/go/bigquery"
	"github.com/googleapis/google-cloud-go-testing/bigquery/bqiface"
)

func main() {
	ctx := context.Background()
	c, _ := bigquery.NewClient(ctx, "projname") // assume err != nil

	client := bqiface.AdaptClient(c)
	query := client.Query("SELECT ...") // real select statement that should work
	config := bqiface.QueryConfig{
		QueryConfig: bigquery.QueryConfig{
			// empty config should have no effect
		},
	}
	query.SetQueryConfig(config)
	query.Run(ctx) // fails
}

```

**Comment by jadekler** [comment]
I'm a bit confused. There is no `Query(q string)`. Do you mean `s`, as in `Query(s string)`?

Could you expand your repro code to something more complete (that I can `go run`) to showcase what you mean?

**Comment by addcninblue** [comment]
I updated my code above.

The `Query(q string)` I mentioned was from `bigquery.Client.Query`, and the one that's eventually run is 

https://github.com/googleapis/google-cloud-go-testing/blob/master/bigquery/bqiface/adapters.go#L62

The part that has a possible bug is 
https://github.com/googleapis/google-cloud-go-testing/blob/eb75b5d3b5349f64f4e398e2dbd76310dbc88672/bigquery/bqiface/adapters.go#L192
since the entire config is overwritten. 

To make the original code I wrote work, you would have to specify the query twice:
```
import (
	"context"

	"cloud.google.com/go/bigquery"
	"github.com/googleapis/google-cloud-go-testing/bigquery/bqiface"
)

func main() {
	ctx := context.Background()
	c, _ := bigquery.NewClient(ctx, "projname") // assume err != nil

	client := bqiface.AdaptClient(c)
	query := client.Query("SELECT ...") // real select statement that should work
	config := bqiface.QueryConfig{
		QueryConfig: bigquery.QueryConfig{
			Q: "SELECT ..." // this will make it work again
		},
	}
	query.SetQueryConfig(config)
	query.Run(ctx) // fails
}
```

**Comment by jadekler** [comment]
Ah! Thank you. This is working as intended AFAICT since the query itself is part of the config.
