### ISSUE TITLE
update cloud.google.com/go and google.golang.org/api

### ISSUE THREAD

**Issue by ukai** [googleapis/google-cloud-go-testing#25]
go.mod referes cloud.google.com/go v0.36.0, but it refers

```
cloud.google.com/go@v0.36.0 go.opencensus.io@v0.18.0
go.opencensus.io@v0.18.0 git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999
```

and git.apache.org is unreachable (see https://github.com/golang/go/issues/34016)

please update cloud.google.com/go version.

**Comment by ukai** [comment]
also google.golang.org/api v0.1.0 ?

```
google.golang.org/api@v0.1.0 go.opencensus.io@v0.18.0
```

**Comment by jadekler** [comment]
I'm sorry, I don't fully understand this question. Are you running into an error? If so, could you post the full error log?

**Comment by bcmills** [comment]
@jadekler, the turndown of `git.apache.org` broke some builds for users who don't already have the dependency cached and aren't using a module mirror.

The bad dependency has already been removed from `cloud.google.com/go` and `google.golang.org/api` (by @odeke-em in https://code-review.googlesource.com/c/gocloud/+/40311, and by you in https://code-review.googlesource.com/c/google-api-go-client/+/40330 respectively).

@ukai, it should suffice for you to upgrade your dependencies on `cloud.google.com/go` and `google.golang.org/api` to the latest releases.

**Comment by ukai** [comment]
@bcmills it's not for google-api-go-client, but google-cloud-go-testing
https://github.com/googleapis/google-cloud-go-testing/blob/master/go.mod
```
module github.com/googleapis/google-cloud-go-testing

require (
	cloud.google.com/go v0.36.0
	golang.org/x/lint v0.0.0-20190301231843-5614ed5bae6f
	golang.org/x/tools v0.0.0-20190305160728-f8c04913dfb7
	google.golang.org/api v0.1.0
	honnef.co/go/tools v0.0.0-20190215041234-466a0476246c
)
```

**Comment by jadekler** [comment]
https://github.com/googleapis/google-cloud-go-testing/pull/27

**Comment by ukai** [comment]
thanks! #27 fixes this.
