### ISSUE TITLE
datastore: How to interchange the dsfiface.client with real datastore

### ISSUE THREAD

**Issue by chaudharisuresh997** [googleapis/google-cloud-go-testing#34]
In your file adapters.go you have passed calls to real datastore so how you have done mocking.
I will really appreciate if you give one small example of
you created mock datastore client passed it to real code which expect datastore.client and it executes the mock client.

**Comment by tbpg** [comment]
You can find the GoDoc for the `dsiface` package here: https://pkg.go.dev/github.com/googleapis/google-cloud-go-testing@v0.0.0-20191008195207-8e1d251e947d/datastore/dsiface?tab=doc

The idea is that in your code, you wouldn't use a `datastore.Cient`, you would use a `dsiface.Client`. Then the client can either be your own mock of that interface, or the actual `datastore.Client` (that you transform with `dsiface.AdaptClient`. I hope that makes sense.

I'm going to close this, but feel to let us know if you have additional questions.
