### ISSUE TITLE
psiface how to access to pubsub.Subscription

### ISSUE THREAD

**Issue by jeandanielJouanneaud** [googleapis/google-cloud-go-testing#35]
Hello, using psiface.AdaptClient method avoid us to retreive the original pubsub.subscription.

`	adaptPubSubClient := psiface.AdaptClient(pubSubClient)
        subscription := adaptPubSubClient.Subscription(conf.SubName)
`

We want to set the sub.ReceiveSettings.MaxOutstandingMessages parameter.
How can we do this with psiface ?

`sub.ReceiveSettings.MaxOutstandingMessages = conf.MaxOutstandingMessages`

Best,

**Comment by codyoss** [comment]
I would suggest defining your own interfaces if you are looking to [mock interactions](https://github.com/googleapis/google-cloud-go/blob/master/testing.md#testing-using-mocks). Also, pubsub does have a fake library you can make use of in tests: [pstest](https://pkg.go.dev/cloud.google.com/go/pubsub/pstest)
