### ISSUE TITLE
[question] How can I unittest my code that depends on storage.Client

### ISSUE THREAD

**Issue by droslean** [googleapis/google-cloud-go-testing#39]
Example: 

```go
func myFunc(client *storage.Client) {
// doing stuff
}

func TestMyFunc(t *testing.T){

// cases....

fakeClient := ???????
myfunc(fakeClient) 
}
```

**Comment by codyoss** [comment]
If you are trying to use the interfaces provided in this repo, please take a look at the example: https://github.com/googleapis/google-cloud-go-testing/blob/master/storage/stiface/examples_test.go#L24-L33.

Another option you may consider is define your own interface over the storage client with just the methods you use. Then you can pass the concrete type at runtime while providing a mock for test-time.
