### ISSUE TITLE
cloud tasks interface?

### ISSUE THREAD

**Issue by banksean** [googleapis/google-cloud-go-testing#40]
My team (I work on Chrome Operations, FWIW) has some new code that uses cloud.google.com/go/cloudtasks/apiv2

We'd like to write tests for it. Do you have a plan/priority to make a similar package for Cloud Tasks, e.g. cloudtasks/ctinterface/... ?

**Comment by codyoss** [comment]
We do not. I would suggest either creating your own interface for the methods you need or keep using a the concrete client and use a fake in the test.
