### ISSUE TITLE
bigquery: add support for Inserter() function

### ISSUE THREAD

**Issue by Omar-Ali** [googleapis/google-cloud-go-testing#42]
Newer version of BigQuery pkg contains Inserter() function as Uploader() function is being deprecated, which is not supported here in bigquery iface.

**Describe the solution you'd like:**
Please add support for the new version.

**Describe alternatives you've considered:**
I tried to write it and create a branch but seems like no outside contributions are allowed.

**Comment by codyoss** [comment]
Hey @Omar-Ali what bigquery iface are you talking about?

**Comment by codyoss** [comment]
Hey @Omar-Ali this repository is no longer receiving updates. Interfaces in Go are implicit, meaning you can define them in your code and the BigQuery client will still fulfill them. If you are looking for general strategies for testing against client I suggest checking out our testing guide: https://github.com/googleapis/google-cloud-go/blob/master/testing.md
